"""EPANET INP text exporters."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import geopandas as gpd
from shapely.geometry import LineString


REQUIRED_JUNCTION_FIELDS = ("node_id", "elevation_m")
REQUIRED_PIPE_FIELDS = (
    "pipe_id",
    "from_node",
    "to_node",
    "length_m",
    "diameter_mm",
    "roughness",
    "minor_loss",
    "status",
)


def write_basic_inp(
    junctions: gpd.GeoDataFrame,
    pipes: gpd.GeoDataFrame,
    outdir: str | Path,
    name: str,
    flow_units: str = "LPS",
    headloss: str = "H-W",
) -> Path:
    """Write a minimal EPANET INP file from junctions and pipes."""
    inp_dir = Path(outdir) / "inp"
    inp_dir.mkdir(parents=True, exist_ok=True)
    output_path = inp_dir / f"{name}.inp"
    output_path.write_text(
        build_basic_inp_text(
            junctions=junctions,
            pipes=pipes,
            flow_units=flow_units,
            headloss=headloss,
        ),
        encoding="utf-8",
    )
    return output_path


def build_basic_inp_text(
    junctions: gpd.GeoDataFrame,
    pipes: gpd.GeoDataFrame,
    flow_units: str = "LPS",
    headloss: str = "H-W",
) -> str:
    """Build a minimal EPANET INP text representation."""
    _require_fields(junctions, REQUIRED_JUNCTION_FIELDS, "junctions")
    _require_fields(pipes, REQUIRED_PIPE_FIELDS, "pipes")

    lines: list[str] = []
    lines.extend(_title_section())
    lines.extend(_options_section(flow_units=flow_units, headloss=headloss))
    lines.extend(_junctions_section(junctions))
    lines.extend(_pipes_section(pipes))
    lines.extend(_coordinates_section(junctions))
    lines.extend(_vertices_section(pipes))
    lines.extend(["[END]", ""])
    return "\n".join(lines)


def _title_section() -> list[str]:
    return [
        "[TITLE]",
        "; Generated by epanet_tools",
        "",
    ]


def _options_section(flow_units: str, headloss: str) -> list[str]:
    return [
        "[OPTIONS]",
        f" UNITS              {flow_units}",
        f" HEADLOSS           {headloss}",
        "",
    ]


def _junctions_section(junctions: gpd.GeoDataFrame) -> list[str]:
    lines = [
        "[JUNCTIONS]",
        ";ID                 Elevation      Demand         Pattern",
    ]
    for _, row in junctions.iterrows():
        node_id = _text(row["node_id"])
        elevation = _number(row["elevation_m"])
        lines.append(f" {node_id:<18} {elevation:<14} 0")
    lines.append("")
    return lines


def _pipes_section(pipes: gpd.GeoDataFrame) -> list[str]:
    lines = [
        "[PIPES]",
        ";ID                 Node1              Node2              Length         Diameter       Roughness      MinorLoss      Status",
    ]
    for _, row in pipes.iterrows():
        pipe_id = _text(row["pipe_id"])
        from_node = _text(row["from_node"])
        to_node = _text(row["to_node"])
        length = _number(row["length_m"])
        diameter = _number(row["diameter_mm"])
        roughness = _number(row["roughness"])
        minor_loss = _number(row["minor_loss"])
        status = _text(row["status"])
        lines.append(
            f" {pipe_id:<18} {from_node:<18} {to_node:<18} "
            f"{length:<14} {diameter:<14} {roughness:<14} {minor_loss:<14} {status}"
        )
    lines.append("")
    return lines


def _coordinates_section(junctions: gpd.GeoDataFrame) -> list[str]:
    lines = [
        "[COORDINATES]",
        ";Node               X-Coord          Y-Coord",
    ]
    for _, row in junctions.iterrows():
        node_id = _text(row["node_id"])
        geom = row.geometry
        lines.append(f" {node_id:<18} {_number(geom.x):<16} {_number(geom.y)}")
    lines.append("")
    return lines


def _vertices_section(pipes: gpd.GeoDataFrame) -> list[str]:
    lines = [
        "[VERTICES]",
        ";Link               X-Coord          Y-Coord",
    ]
    for _, row in pipes.iterrows():
        geom = row.geometry
        if not isinstance(geom, LineString):
            continue
        coords = list(geom.coords)
        if len(coords) <= 2:
            continue
        pipe_id = _text(row["pipe_id"])
        for coord in coords[1:-1]:
            lines.append(f" {pipe_id:<18} {_number(coord[0]):<16} {_number(coord[1])}")
    lines.append("")
    return lines


def _require_fields(data: gpd.GeoDataFrame, fields: tuple[str, ...], layer_name: str) -> None:
    missing = [field for field in fields if field not in data.columns]
    if missing:
        msg = f"Missing required fields in {layer_name}: {', '.join(missing)}"
        raise ValueError(msg)


def _number(value: Any) -> str:
    number = float(value)
    return f"{number:.6f}".rstrip("0").rstrip(".")


def _text(value: Any) -> str:
    return str(value).strip()
